# Generated by Django 6.0.3 on 2026-04-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_course_description_course_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
