# Generated by Django 6.0.3 on 2026-04-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_course_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reviews_quantity',
        ),
    ]
